- name: Set up www.ocascata.cz
  hosts: all
  vars:
    repo: https://github.com/tasuki/ocascata.git
    chdir: /var/www/cz.ocascata/www
  tasks:
    - name: "Clone {{ repo }} to {{ chdir }}"
      import_tasks: ../../roles/git-deployments/tasks/clone.yml
    - name: Install dependencies
      become_user: root
      apt:
        pkg: [ ruby-full, bundler, build-essential ]
    - name: Bundle install
      become_user: root
      bundler:
        chdir: "{{ chdir }}"
        state: present

    - name: "Check whether {{ chdir }}/_site/ exists"
      stat:
        path: "{{ chdir }}/_site/"
      register: generated_site
    - name: Publish
      make:
        chdir: "{{ chdir }}"
      when: not generated_site.stat.exists
