- name: Set up tsumego.tasuki.org
  hosts: all
  vars:
    repo: https://github.com/tasuki/tsumego-web.git
    chdir: /var/www/org.tasuki/tsumego
  tasks:
    - name: "Clone {{ repo }} to {{ chdir }}"
      import_tasks: ../../roles/git-deployments/tasks/clone.yml
    - name: Install dependencies
      become: true
      apt:
        pkg: [ ruby-full, bundler, build-essential ]
    - name: Bundle install
      bundler:
        chdir: "{{ chdir }}"
        state: present

    - name: "Check whether {{ chdir }}/build/ exists"
      stat:
        path: "{{ chdir }}/build/"
      register: generated_site
    - name: Publish
      make:
        chdir: "{{ chdir }}"
      when: not generated_site.stat.exists
