- name: Set up enchiridion.tasuki.org
  hosts: all
  vars:
    repo: https://github.com/tasuki/sbs-enchiridion.git
    chdir: /var/www/org.tasuki/enchiridion
  tasks:
    - name: "Clone {{ repo }} to {{ chdir }}"
      import_tasks: ../../roles/git-deployments/tasks/clone.yml

    - name: Clone library repo
      import_tasks: sbs-library.yml

    - name: Symlink library
      file:
        src: "/var/www/org.tasuki/sbs/"
        dest: "{{ chdir }}/sbs"
        state: link
