- name: Set up blog.tasuki.org
  hosts: all
  become: true
  vars:
    repo: https://github.com/tasuki/blog.git
    base: /var/www/org.tasuki/blog
  tasks:
    - name: "Clone {{ repo }} to {{ base }}"
      git:
        repo: "{{ repo }}"
        dest: "{{ base }}"
        version: master
    - name: Install dependencies
      apt:
        pkg: [ ruby-full, bundler, build-essential ]
    - name: Bundle install
      bundler:
        chdir: "{{ base }}"
        state: present

    - name: "Check whether {{ base }}/_site/ exists"
      stat:
        path: "{{ base }}/_site/"
      register: blog_site
    - name: Publish blog
      make:
        chdir: "{{ base }}"
      when: not blog_site.stat.exists

