- name: Set up fonts.tasuki.org
  hosts: all
  vars:
    repo: https://github.com/tasuki/fonts.git
    chdir: /var/www/org.tasuki/fonts
  tasks:
    - name: "Clone {{ repo }} to {{ chdir }}"
      import_tasks: ../../roles/git-deployments/tasks/clone.yml
    - name: Install packages
      become: true
      apt:
        pkg: [ composer ]

    - name: "Check whether {{ chdir }}/vendor/ exists"
      stat:
        path: "{{ chdir }}/vendor/"
      register: dependencies_dir
    - name: Install composer dependencies
      make:
        chdir: "{{ chdir }}"
      environment:
        COMPOSER_ALLOW_SUPERUSER: 1
      when: not dependencies_dir.stat.exists
