- name: Set up system.tasuki.org
  hosts: all
  tasks:
    - name: Copy files
      copy:
        src: "org.tasuki.system/{{ item.src }}"
        dest: "/var/www/org.tasuki/system"
      loop:
        - { src: "awstats-list.php" }
        - { src: "munin-highlights.php" }
        - { src: "phpinfo.php" }
