- name: Set up blog.tasuki.org
  hosts: all
  become: true
  vars:
    repo: https://github.com/tasuki/blog.git
    chdir: /var/www/org.tasuki/blog
  tasks:
    - name: "Clone {{ repo }} to {{ chdir }}"
      import_tasks: ../../roles/git-deployments/tasks/clone.yml
    - name: Install dependencies
      apt:
        pkg: [ ruby-full, bundler, build-essential ]
    - name: Bundle install
      bundler: # gem install sassc -v '2.4.0' --source 'https://rubygems.org/'
        chdir: "{{ chdir }}"
        state: present

    - name: "Check whether {{ chdir }}/_site/ exists"
      stat:
        path: "{{ chdir }}/_site/"
      register: generated_site
    - name: Publish
      make:
        chdir: "{{ chdir }}"
      when: not generated_site.stat.exists
