- name: Set up gallery.tasuki.org
  hosts: all
  vars:
    repo: https://github.com/tasuki/gallery.git
    chdir: /var/www/org.tasuki/gallery
  tasks:
    - name: "Clone {{ repo }} to {{ chdir }}"
      import_tasks: ../../roles/git-deployments/tasks/clone.yml

    - name: Install dependencies
      become: true
      apt:
        pkg: [ imagemagick, composer, php-mbstring, php-xml, php-imagick ]

    - name: Copy config file
      copy:
        src: "org.tasuki.gallery/.env.local"
        dest: "{{ chdir }}"
    - name: Writable gallery and var dir
      become: true
      file:
        path: "{{ item }}"
        owner: www-data
        group: www-data
        recurse: true
      loop:
        - "{{ chdir }}/public/gallery/"
        - "{{ chdir }}/var/"
