---
- import_playbook: playbooks/personalize.yml
- import_playbook: playbooks/secure.yml

- name: Set up deployments and web server
  hosts: all
  become: true
  vars_files:
    - vars/global.yml
    - vars/vault.yml
  roles:
    - role: roles/git-deployments
    - role: roles/ssl-cheat
    - role: roles/web-server
    - role: roles/analytics

# Set up concrete websites
- import_playbook: playbooks/sites/org.tasuki.blog.yml
- import_playbook: playbooks/sites/org.tasuki.cv.yml
- import_playbook: playbooks/sites/org.tasuki.enchiridion.yml
- import_playbook: playbooks/sites/org.tasuki.fonts.yml
- import_playbook: playbooks/sites/org.tasuki.gallery.yml
- import_playbook: playbooks/sites/org.tasuki.masonry-ordered.yml
- import_playbook: playbooks/sites/org.tasuki.system.yml
- import_playbook: playbooks/sites/org.tasuki.tsumego.yml
- import_playbook: playbooks/sites/org.tasuki.ttc.yml
- import_playbook: playbooks/sites/org.tasuki.www.yml

# Less important things
- import_playbook: playbooks/monitoring.yml

# TODO:
# letsencrypt
# crons
