---
- import_playbook: playbooks/personalize.yml
- import_playbook: playbooks/secure.yml

- name: Set up deployments and web server
  hosts: all
  become: true
  vars_files:
    - vars/global.yml
    - vars/vault.yml
  roles:
    - role: roles/git-deployments
    - role: roles/ssl-cheat
    - role: roles/ssl-certbot
    - role: roles/web-server
    - role: roles/analytics

# Set up *.tasuki.org
- import_playbook: playbooks/sites/org.tasuki.blog.yml
- import_playbook: playbooks/sites/org.tasuki.cv.yml
- import_playbook: playbooks/sites/org.tasuki.enchiridion.yml
- import_playbook: playbooks/sites/org.tasuki.fonts.yml
- import_playbook: playbooks/sites/org.tasuki.gallery.yml
- import_playbook: playbooks/sites/org.tasuki.masonry-ordered.yml
- import_playbook: playbooks/sites/org.tasuki.system.yml
- import_playbook: playbooks/sites/org.tasuki.tsumego.yml
- import_playbook: playbooks/sites/org.tasuki.ttc.yml
- import_playbook: playbooks/sites/org.tasuki.www.yml

# Set up *.tasuki (handshake)
- import_playbook: playbooks/sites/tasuki.sniper.yml
- import_playbook: playbooks/sites/tasuki.www.yml


# Less important things
- import_playbook: playbooks/monitoring.yml
