---
- import_playbook: playbooks/personalize.yml
- import_playbook: playbooks/secure.yml

- name: Set up deployments and web server
  hosts: all
  become: true
  vars_files:
    - vars/global.yml
    - vars/vault.yml
  roles:
    - role: roles/git-deployments
    - role: roles/web-server

# Set up concrete websites
- import_playbook: playbooks/sites/org.tasuki.blog.yml

# TODO:
# letsencrypt
# awstats
# munin
# crons
