---
# Initial basics
- import_playbook: playbooks/personalize.yml
- import_playbook: playbooks/secure.yml

# Deployments
- import_playbook: playbooks/git-deployments.yml
- import_playbook: playbooks/deploy-users.yml

# SSL & Web Server
- import_playbook: playbooks/ssl.yml
- import_playbook: playbooks/web-server.yml

# Contents of websites
- import_playbook: playbooks/sites.yml

# Analytics & Monitoring
- import_playbook: playbooks/analytics.yml
- import_playbook: playbooks/monitoring.yml
