---
- name: Create protected directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { path: '/etc/letsencrypt/archive/', mode: '700' }
    - { path: '/etc/letsencrypt/live/',    mode: '700' }

- include_tasks: domain.yml
  vars:
    domain: tasuki.org
- include_tasks: domain.yml
  vars:
    domain: lsg.go.art.pl
