---
- name: Create www directory
  file:
    path: "/var/www/{{ item.domain }}/{{ item.subdomain }}"
    state: directory
- name: Create repo
  command: "git init /var/www/{{ item.domain }}/{{ item.subdomain }}"
  args:
    creates: "/var/www/{{ item.domain }}/{{ item.subdomain }}/.git"
- name: Symlink post-commit hook
  file:
    src: "/var/git/hooks/post-commit"
    dest: "/var/www/{{ item.domain }}/{{ item.subdomain }}/.git/hooks/post-commit"
    state: link
- name: Symlink post-merge hook
  file:
    src: "/var/git/hooks/post-merge"
    dest: "/var/www/{{ item.domain }}/{{ item.subdomain }}/.git/hooks/post-merge"
    state: link
- name: Add hub remote
  import_tasks: remote-add.yml
  vars:
    name: hub
    repo: "/var/git/{{ item.domain }}/{{ item.subdomain }}"
    chdir: "/var/www/{{ item.domain }}/{{ item.subdomain }}"
