---
- name: Create git directory
  file:
    path: "/var/git/{{ item.domain }}/{{ item.subdomain }}"
    state: directory
- name: Create bare repo in git directory
  command: "git init --bare /var/git/{{ item.domain }}/{{ item.subdomain }}"
  args:
    creates: "/var/git/{{ item.domain }}/{{ item.subdomain }}/HEAD"

- name: Create www directory
  file:
    path: "/var/www/{{ item.domain }}/{{ item.subdomain }}"
    state: directory
- name: Create repo
  command: "git init /var/www/{{ item.domain }}/{{ item.subdomain }}"
  args:
    creates: "/var/www/{{ item.domain }}/{{ item.subdomain }}/.git"
- name: Symlink post-commit hook
  file:
    src: "/var/git/hooks/post-commit"
    dest: "/var/www/{{ item.domain }}/{{ item.subdomain }}/.git/hooks/post-commit"
    state: link
- name: Symlink post-merge hook
  file:
    src: "/var/git/hooks/post-merge"
    dest: "/var/www/{{ item.domain }}/{{ item.subdomain }}/.git/hooks/post-merge"
    state: link
- name: Add hub remote
  command:
    cmd: "git remote add hub /var/git/{{ item.domain }}/{{ item.subdomain }}"
    chdir: "/var/www/{{ item.domain }}/{{ item.subdomain }}"
  register: add_result
  changed_when: add_result.rc == 0
  failed_when:
    - add_result.rc != 0
    - add_result.stderr | default('') is not search("remote .* already exists")
