- name: Create www/git directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  loop:
    - /var/www/
    - /var/git/
- name: Create hooks directory
  file:
    path: /var/git/hooks
    state: directory
- name: Copy templates
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  loop:
    - { src: 'README.md',   dest: '/var/git/',       mode: '644' }
    - { src: 'post-commit', dest: '/var/git/hooks/', mode: '755' }
    - { src: 'post-merge',  dest: '/var/git/hooks/', mode: '755' }
    - { src: 'post-update', dest: '/var/git/hooks/', mode: '755' }
- name: Create empty repos in /var/www
  include_tasks: create-www-repo.yml
  loop:
    "{{ projects }}"
