---
- name: Install AWStats
  apt:
    pkg:
      - awstats
      - libgeo-ip-perl
      - geoip-database
- name: Copy local conf
  copy:
    src: awstats.conf.local
    dest: /etc/awstats/
- name: Create website configs
  template:
    src: site.conf
    dest: "/etc/awstats/awstats.{{ item.domain }}.{{ item.subdomain }}.conf"
  loop:
    "{{ projects }}"
- name:
  lineinfile:
    path: "/etc/crontab"
    regex: "awstats"
    line: >-
      5 */03  * * *   root    perl
      /usr/share/doc/awstats/examples/awstats_updateall.pl now
      -awstatsprog=/usr/lib/cgi-bin/awstats.pl
