# For the KNOWN_HOSTS thing:
# `ssh-keyscan -p 678 -t ed25519 tasuki.org`

- name: Create users for deployments
  hosts: all
  become: true
  vars:
    deploy_users:
      - username: deploy_lsg
        pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEgyQyWSME/MpY3p0eO/YOjreN/macJmbVLilHxzfG7\n"
        project_paths:
          - "/var/git/pl.art.go/"
          - "/var/www/pl.art.go/"
      - username: deploy_ocascata
        pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINVOQB5d0AE/KXrICaYUAM1qJV0yiVYm50EehgDAfIZQ\n"
        project_paths:
          - "/var/git/cz.ocascata/"
          - "/var/www/cz.ocascata/"

  tasks:
    - name: Configure deploy users
      include_tasks: tasks/create-deploy-user.yml
      loop: "{{ deploy_users }}"
      loop_control:
        loop_var: deploy_user
        label: "Configuring user {{ deploy_user.username }}"
