---
- name: Monitoring with Munin
  hosts: all
  become: true
  vars:
    htmldir: "/var/www/org.tasuki/system/munin"
  tasks:
    - name: Install munin
      apt:
        pkg:
          [ munin, munin-node, munin-plugins-extra ]
    - name: Create htmldir
      file:
        path: "{{ htmldir }}"
        state: directory
        owner: munin
        group: munin
    - name: Set htmldir
      lineinfile:
        path: "/etc/munin/munin.conf"
        regex: "htmldir"
        line: "htmldir {{ htmldir }}"
      notify: Restart munin
    - name: Disable apache module, it breaks things
      file:
        path: "/etc/apache2/conf-enabled/munin.conf"
        state: absent
      notify: Restart apache
    - name: Enable apache monitoring
      file:
        src: "/usr/share/munin/plugins/{{ item }}"
        dest: "/etc/munin/plugins/{{ item }}"
        state: link
      loop:
        [ apache_accesses, apache_processes, apache_volume ]
      notify: Restart munin

  handlers:
    - name: Restart munin
      service:
        name: "{{ item }}"
        state: restarted
      loop: [ munin, munin-node ]
    - name: Restart apache
      service:
        name: apache2
        state: restarted
