---
- name: Personalization - dotrc and things I need to exist
  hosts: all
  tasks:
    - name: Update cache once a week
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 604800 # 60 * 60 * 24 * 7

    - name: Install packages
      become: true
      apt:
        pkg:
          [ curl, bash, git, stow # necessary
          , tmux, tmuxinator, zsh, vim-nox, htop, nethogs, units # traditional cli tools
          , jq, fzf, fd-find, ripgrep, bat ] # hip cli tools

    - name: My own dotrc
      shell: curl -s https://raw.githubusercontent.com/tasuki/dotrc/master/install.sh | bash
      args:
        creates: ~/dotrc/

    - name: Use zsh as shell
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
