---
- name: Personalization - dotrc and things I need to exist
  hosts: all
  tasks:
    - name: Update cache once a week
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 604800 # 60 * 60 * 24 * 7

    - name: Install packages
      become: true
      apt:
        pkg:
          [ curl, bash, git, stow # necessary
          , mosh, tmux, tmuxinator, zsh, vim-nox, acl, htop, nethogs, units # traditional cli tools
          , jq, fzf, fd-find, ripgrep, bat ] # hip cli tools

    - name: Install delta
      become: true
      apt:
        deb: https://github.com/dandavison/delta/releases/download/0.12.1/git-delta_0.12.1_amd64.deb

    - name: My own dotrc
      shell: curl -s https://raw.githubusercontent.com/tasuki/dotrc/master/install.sh | bash
      args:
        creates: ~/dotrc/

    - name: Use zsh as shell
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Locales
      become: true
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop:
        - en_US.UTF-8
        - en_DK.UTF-8
        - cs_CZ.UTF-8
