---
- name: Create user
  hosts: all
  become: true
  vars:
    username: vita
  tasks:
    - name: Create user
      user:
        name: "{{ username }}"
        groups: sudo
        password: "$6$lP1Yt8.tEdUYL9$VJ4lw5RDBFvIol9l16rGibssVLLlEtJgbTj4XF4qPV\
                   dFFn1bP5CXdT4q3Y98YnWYZheVACv.8Ijsb8YGHhQyr1"
    - name: Create ~/.ssh/
      file:
        path: "/home/{{ username }}/.ssh/"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "700"
    - name: Authorize pubkey
      copy:
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "700"
        content: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFVDwsBN8MVftFAQtbLqckNvXwHRGbksNTMchlwXxvit\n"
